web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - .:/code
db:
  image: "mysql:5"
  volumes:
    - ./mysql:/etc/mysql/conf.d
    - ./webroot/db:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: scotchbox
